language: go
go:
  - 1.12.x
  - 1.13.x

env:
  global:
    - NODE_VERSION=10.16.3

before_script:
  # use GO111MODULE=off otherwise libs can't be updates inside vendor/
  - GO111MODULE=off go get github.com/valyala/quicktemplate # for tests
  - GO111MODULE=off go get github.com/pkg/errors # for tests
  - nvm install "${NODE_VERSION}"

script:
  - time make fast_check_generated
  - time make test

branches:
  only: # speed up CI: don't build pull requests twice
    - "master"

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - echo "travis go version='$TRAVIS_GO_VERSION'"

# needed for the docker pipe
services:
- docker

deploy:
- provider: script
  skip_cleanup: true
  script:
    - make test_race
    - curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    # it's important to build on the newest version of go:
    condition: $TRAVIS_GO_VERSION =~ ^1\.13
