sudo: false
language: go
go:
  - 1.11.x
  - 1.12.x

before_script:
  - go get github.com/valyala/quicktemplate # for tests
  - go get github.com/pkg/errors # for tests

script: make check_generated test

branches:
  only: # speed up CI: don't build pull requests twice
    - "master"

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - echo "travis go version='$TRAVIS_GO_VERSION'"

# needed for the docker pipe
services:
- docker

deploy:
- provider: script
  skip_cleanup: true
  script:
    - make test_race
    - curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    # it's important to build on the newest version of go:
    condition: $TRAVIS_GO_VERSION =~ ^1\.12
