[[constraint]]
  name = "github.com/golangci/revgrep"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "sourcegraph.com/sourcegraph/go-diff"

[[constraint]]
  name = "github.com/golangci/govet"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-ps"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/unconvert"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/go-misc"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/goconst"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/check"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/gocyclo"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/gofmt"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/maligned"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/ineffassign"

[[constraint]]
  branch = "master"
  name = "github.com/OpenPeeDeeP/depguard"

[[constraint]]
  branch = "master"
  name = "github.com/golangci/unparam"
