version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "dependency"
    ignored_updates:
      - match: # ignore forked linters because of their versioning issues. TODO: fix it.
          dependency_name: "github.com/golangci/*"
